// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSys.Data.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public DateTime? FoundedDate { get; set; }

    public string Website { get; set; }

    public bool IsActive { get; set; }

    public string Industry { get; set; }
}